spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.158.57:8848
    alicloud:
      access-key: LTAI4FwvfjSycd1APnuG9bjj
      secret-key: O6xaxyiWfSIitcOkSuK27ju4hXT5Hl
      oss:
        endpoint: oss-cn-beijing.aliyuncs.com
        bucket: caowei-leyou

  application:
    name: gulimall-third-party

server:
  port: 30000
