server:
  port: 10909
knife4j:
  enableAggregation: true
  nacos:
    enable: true
    serviceUrl: http://47.101.158.57:8848/nacos/
    routes:
      - name: 订单服务
        serviceName: gulimall-product
        location: /v2/api-docs?group=default
        servicePath: /gulimall-product
#      - name: 用户体系
#        serviceName: service-user
#        location: /aub/v2/api-docs?group=default
#        servicePath: /