server:
  port: 9000

spring:
  cloud:
    nacos:
      discovery:
        server-addr: 47.101.158.57:8848
  datasource:
    username: root
    password: root
    url: jdbc:mysql://47.101.158.57:3306/gulimall_oms
    driver-class-name: com.mysql.jdbc.Driver
  main:
    allow-bean-definition-overriding: true
mybatis-plus:
  mapper-locations: classpath:/mapper/**/*.xml
  global-config:
    db-config:
      id-type: auto